In [1]:
import ipwhois


In [3]:
obj = ipwhois.IPWhois('64.233.177.139')

/home/omid/.conda/envs/iot_new/lib/python3.6/site-packages/ipwhois/net.py:138: UserWarning: allow_permutations has been deprecated and will be removed. It is no longer needed, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '


In [5]:
res=obj.lookup()

AttributeError: 'IPWhois' object has no attribute 'lookup'

In [6]:
import socket

In [11]:
socket.gethostbyaddr("13.59.232.129")

('ec2-13-59-232-129.us-east-2.compute.amazonaws.com', [], ['13.59.232.129'])

In [1]:
import numpy as np

In [3]:
a = np.array( [1,2,3,4] )
b= np.array([5,6,7,8])

c= np.append( a,b )

In [1]:
import numpy as np 
a= np.array([[1,2],[2,3],3,4,4,5])

In [2]:
b= np.expand_dims(a,axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5]])

In [11]:
a= [[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]]

In [13]:
def do_it (x):
    return np.sum(x)

In [17]:
aa =map( lambda x: do_it( x ) , a )
 
[print(x) for x in aa]

ZeroDivisionError: division by zero

In [19]:
import random 
random.random()

0.04233039545075101

In [27]:
def acc_match( true, pred ):
    
    return (len( [ x  for x  in  [np.sum(np.abs( true[i]- pred[i] )) for i in range(len(true))] if x  == 0]))*1.0 / len(true)
    
    
    

 

acc_match( np.array( [[0,10,0,0],[0,10,0,0]]), np.array([[0,0,0,0],[0,10,0,0]]) )


0.5

In [68]:
a = np.array([[1,2],[2,2],[3,2],[4,3],[5,4],[6,4]])
b =  np.array([[1,232],[2,12],[3,22],[434,3],[555,4],[6,4]])

In [71]:
c =np.average( a ,axis=1 )

In [72]:
c

array([1.5, 2. , 2.5, 3.5, 4.5, 5. ])

In [63]:
a

array([[1, 2],
       [2, 2],
       [3, 2],
       [4, 3],
       [5, 4],
       [6, 4]])

In [39]:
def acc_match_wierd( true, pred ):
    """
    returns exact mathc accuracy
    """
    level = 6 
    switch = 11
    threeAxis=13
    accel = 0 
    status=10
    contact=5
    
    counter  = 0 
    for i in range( len (true) ):
        if np.sum(np.abs( true[i]- pred[i] ))==0 :
            counter+=1
        else : 
            temp = np.zeros(len(true[0]))
            temp[level]=1
            temp[switch]=1
            if np.sum(true[i] * temp )==2 :
                temp = np.ones(len(true[0]) )
                temp[level] = 0
                if np.sum( np.abs( (true[i]*temp) - pred[i]  ) ) ==0:
                    counter+=1
                    continue
            
            temp = np.zeros(len(true[0]))
            temp[threeAxis]=1
            temp[accel]=1
            if np.sum(true[i] * temp )==2 :
                temp = np.ones(len(true[0]) )
                temp[threeAxis] = 0
                if np.sum( np.abs( (true[i]*temp) - pred[i]  ) ) ==0:
                    counter+=1
                    continue
            
            temp = np.zeros(len(true[0]))
            temp[status]=1
            temp[contact]=1
            if np.sum(true[i] * temp )==2 :
                temp = np.ones(len(true[0]) )
                temp[status] = 0
                if np.sum( np.abs( (true[i]*temp) - pred[i]  ) ) ==0:
                    counter+=1
                    continue
            
            
    
    return counter*1.0 / len(true)


true = np.zeros(15)
pred= np.zeros(15)

level = 6 
switch = 11
threeAxis=13
accel = 0 
status=10
contact=5

true[level]=1
true[switch]=1

pred[switch]=1

acc_match_wierd( [true, np.ones(15)],[pred,np.zeros(15) ] )

0.5

In [49]:
def acc_match_wierd( true, pred ):
    """
    returns exact mathc accuracy
    """
    level = 6 
    switch = 11
    threeAxis=13
    accel = 0 
    status=10
    contact=5
    
    counter  = 0 
    for i in range( len (true) ):
        if np.sum(np.abs( true[i]- pred[i] ))==0 :
            counter+=1
        else : 
            t_rec = np.array(list( pred[i]))
            
            if true[i][level]==1 and true[i][switch]==1 and t_rec[switch]==1 :
                t_rec[level]=1
            
            if true[i][threeAxis]==1 and true[i][accel]==1 and t_rec[accel]==1:
                t_rec[threeAxis] =1
            
            if true[i][status]==1 and true[i][contact]==1 and t_rec[contact]==1:
                t_rec[status]=1
            print(t_rec , true[i])    
            if np.sum(np.abs( true[i]- t_rec ))==0 :
                counter+=1   
            
             
            
    
    return counter*1.0 / len(true)

In [50]:
true = np.zeros(15)
pred= np.zeros(15)

level = 6 
switch = 11
threeAxis=13
accel = 0 
status=10
contact=5

true[level]=1
true[switch]=1

pred[switch]=1

acc_match_wierd( [true, np.ones(15)],[pred,np.zeros(15) ] )

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


0.5